"""trades table

Revision ID: 288bee75575d
Revises: 
Create Date: 2019-02-11 00:02:20.259660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288bee75575d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    # ### end Alembic commands ###
